version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - web_db
      - redis
  
  web_db:
    image: mysql:8
    environment:
      - MYSQL_USER=dbUser
      - MYSQL_PASSWORD=dbUser
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    command: --init-file db/app-db-init.sql
    volumes:
      - ./Database/appdata:/docker-entrypoint-initdb.d
    restart: always 
  redis:
    image: redis
