services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS WebProject; CREATE DATABASE IF NOT EXISTS WebProjectIdentity;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - 3306:3307
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  redis-data:
  mysql-data:
